### ISSUE TITLE
Add the ability to use columns types inside the excel exported document.

### ISSUE THREAD

**Issue by ghost** [DataTables/Buttons#141]
DataTables have already the possibility to set columns types:
https://datatables.net/reference/option/columns.type

The idea is use that ability to generate a well formatted excel file.

**Comment by DataTables** [comment]
To some extent [this is possible already](https://github.com/DataTables/Buttons/blob/c6b781ad22ce17e44cc92411b00fe76754f0f363/js/buttons.html5.js#L751). It uses automatic detection on a per cell basis which could be extended.

**Comment by lestcape** [comment]
I don' t know how feasible will be the automatically detection, but directly set the format is 100% secure. If this can be fully resolved with only automation, not one will lost the time to ask the user about the type of his columns in Excel or Libre Office.

I think, the automation is so good when there are not predefined types, but already there are, the predefined values need to be considered first.

In any case, it is very good that there is automatic detection.

I just not updated the DataTables to see that, because we want a responsive design and is not full-fill yet in recent versions with complex headers. I know you have that in mind i want to wait, because really i was try to fix it but I could not achieve it.

Thanks for take it in consideration and for all work done...

**Comment by lestcape** [comment]
I have the time to test the automatic detection in **Buttons-1.5.1**

In our scope, we use an special _id_ to identify in a survey an individual person using an special concatenation of _**state+municipality+locality+area+apple+house+.+people#**_ 

When you export this data to excel using the automation this is the result that we can see:

This is an example string in that format:
_10004001508029990041.01_

This is what i can see in excel after export it:
_10004001508020000000.00_

**Comment by DataTables** [comment]
You need to make it a "string" rather than a number. You could do that by simply adding a space at the end of your string, or if you need to use the `customize` callback to check the automatic type from a number to a string.

This is because it is an IEEE754 number which has limited precision.

**Comment by lestcape** [comment]
Yes i know, the parser take it as numeric and we want it as string.

Add an space it's not a good idea for us and a customize callback is only a good idea if will be implemented it using the original request, because we create a lot of survey per years and of course, they are different in a lot of variables. So, i can not create an specific callback for an specific case. 

Probably we will ending marking all columns as string, instead of try to find the appropriate type automatically or waverer. As we use an old version, try to implement it as the original request is not useful for anyone, also not for us, as we will need to use a new version in some point in the future.

Thanks.

**Comment by AllanJard** [comment]
Closing as stale.
