### ISSUE TITLE
Add flashExport.swf

### ISSUE THREAD

**Issue by Worthy7** [DataTables/Buttons#152]
It seems flashExport.swf is being called from the cdn. Can you please include this in the repo so that it can be referenced accordingly?
I understand it is for convenience, but if a user is deciding to download this repo/npm package then that means they are planning to use it locally. 
I actually think the swf file should be referenced locally by default because of this, but I'm not sure how to "remind" a user to include it.

**Comment by DataTables** [comment]
The swf [is in the repo](https://github.com/DataTables/Buttons/tree/master/swf). [This example](https://datatables.net/extensions/buttons/examples/flash/swfPath.html) shows how you can set the path to have it on your server. It is included on the CDN only because people did forget it all the time.

That said, that Flash version isn't going to be supported much longer.

**Comment by Worthy7** [comment]
My bad, I meant the NPM package

**Comment by DataTables** [comment]
Got it now - thanks! Yup I agree - [committed in here](https://github.com/DataTables/Dist-DataTables-Buttons/commit/b4a1cb055d1710c526d46766b91e9cf1a4697198).

**Comment by Worthy7** [comment]
Is this a good time to ask how long/why the flash version won't be supported much longer?

**Comment by DataTables** [comment]
The reason to drop it is that browsers are actively trying to kill Flash off, and Adobe are going to stop supporting [Flash at all by the end of 2020](https://www.theverge.com/2017/7/25/16026236/adobe-flash-end-of-support-2020).

Rather than putting development time into a dead end technology, it doesn't seem worth continuing to develop for it. If legacy browser support is still required, then the older versions of Buttons (including the up coming 1.5.4 release) are available.

I'm not certain when exactly I'll remove the Flash support - whenever it becomes more than zero maintenance or new features need to be added. It might be that 1.5.x is the last series to support it.

Allan
