### ISSUE TITLE
Print Selected

### ISSUE THREAD

**Issue by MuellerMatthew** [DataTables/Buttons#34]
http://datatables.net/extensions/buttons/examples/print/select.html  <-- this example is no longer functional. The custom 'Print selected' button doesn't work.

**Comment by DataTables** [comment]
Hi, - this has already been fixed with the nightly versions of DataTables and Buttons. I'm trying to find the conversation about it from earlier today and the git commit that resolved it a week or two back, but failing on both accounts at the moment. Either way, try the nightly and it will work - the site uses the release version.

**Comment by MuellerMatthew** [comment]
Thank you for your response.  I found your fix:  https://github.com/DataTables/Buttons/commit/75d79487b60613eaea3b72f29058dc6565bf923b
