### ISSUE TITLE
Right-aligned values become left-aligned on Print button

### ISSUE THREAD

**Issue by hawkeye64** [DataTables/Buttons#38]
I'm not sure if I am doing this correctly, but I have two columns that are right-justified. When you click the Print button, they become left-justified on the proposed print. I'm using your corrected Fiddle from my last issue (btw, thanks for looking into it). Am I using the "columnDefs" correctly?

https://jsfiddle.net/642546ff/2/

**Comment by hawkeye64** [comment]
Also, maybe you can tell me why the excel and pdf buttons don't show up. Thanks!

**Comment by DataTables** [comment]
The print output simply produces an HTML table with no class information - which is why there is no alignment on the table. You would need to use the `customize` option of the [print button type](http://datatables.net/reference/button/print) to manipulate the generated table if that is what you want.

If you search the DataTables site for "print button align" you'll find a few discussions on this topic - including [this one](https://datatables.net/forums/discussion/29797/).

The Excel and PDF buttons are now shown as their dependencies have not being loaded. See the documentation here:

* http://datatables.net/reference/button/pdfHtml5
* http://datatables.net/reference/button/excelHtml5

**Comment by hawkeye64** [comment]
Thanks! I got the Excel and PDF buttons displaying on the Fiddle, but now, I've run into the similar issue as before when clicking the Excel button, it throws an error:

Uncaught TypeError: a[c].match is not a function. 

This is with the nightly buttons.html5.min.js

**Comment by DataTables** [comment]
Can you try the version of the file in this repo please. I've just been applying a few fixes for a similar issue reported in the forums.

If you could post future support requests in the forums that would be much appreciated. That's my primary support channel.

**Comment by hawkeye64** [comment]
My apologies. I'll try searching the forums. I'm not sure what you mean by "Can you try the version of the file in this repo please"?

**Comment by DataTables** [comment]
The files [here](https://github.com/DataTables/Buttons/tree/master/js). They contain unreleased fixes.

**Comment by hawkeye64** [comment]
Yep, those worked! Thanks.
