### ISSUE TITLE
Missing ui- class on DT defaults

### ISSUE THREAD

**Issue by cdaringe** [DataTables/Buttons#54]
Hey Allan!

[Here](https://github.com/DataTables/Buttons/blob/master/js/buttons.jqueryui.js#L45) you have defined the default classes for jquery ui buttons.  I'm not a css design expert, but _I think_ perhaps `'ui-corner-all'` is missing?  When I look at the jQuery theme roller site, the defaults have `'ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only'`.

Feel free to close if it's a non issue.  Thx!

-Chris

**Comment by DataTables** [comment]
Hi Chris,

Thanks for bringing this up. The reason I haven't got `ui-corner-all` on the buttons is that it is applied to each button individually - so each ends up with all four corners rounded and that doesn't look great (imho) when the buttons are next to each other. You can see that by adding the `ui-corner-all` class to the [jQuery UI Buttons example](http://datatables.net/extensions/buttons/examples/styling/jqueryui.html).

What would be nice is if jQuery UI allowed `ui-corner-all` to be applied to the button set and then use `:first-child` and `:last-child` to add rounded corners at the left and right of the button set only. But it doesn't allow that.

The only other option is to use the classes to emulate that, but Buttons doesn't have the ability to add classes to the first / last button only (based on position rather than anything else) primarily because there is no need for it with "modern" CSS.

I think on balance, for the features that jQuery UI has this is not something I'm going to put in. An extra line or two of custom CSS is probably the best fix at the moment.

**Comment by cdaringe** [comment]
Interesting, I understand your point.  Thanks for the thorough explanation!  I ended up just `dom` ing out a container with a special class, spacing out buttons, and adding the class to DT.Buttons.defaults.

Much appreciated!

<img width="345" alt="screen shot 2015-11-05 at 9 27 32 am" src="https://cloud.githubusercontent.com/assets/1003261/10976229/89399822-839f-11e5-97e3-e0da2116d0f8.png">
