### ISSUE TITLE
excel exports number as string

### ISSUE THREAD

**Issue by chipco** [DataTables/Buttons#95]
Some numbers are interpreted as strings while exporting.

For example numbers with thousands delimiters: `20,944,000.02`. Also in some locals valid numbers can be `20.944.000,02`. Unfortunately js `typeof` or `Number()` do a bad job at working such numbers. Probably some custom regExp could do a better job.

**Comment by chipco** [comment]
Something like this `^\$?-?(\d{1,3}([\,\.]\d{3})*|(\d+))([\,\.]\d*)?$`

[This condition](https://github.com/DataTables/Buttons/blob/master/js/buttons.html5.js#L1060) should be `if (row[i].match(/^\$?-?(\d{1,3}([\,\.]\d{3})*|(\d+))([\,\.]\d*)?$/) !==null)`

**Comment by DataTables** [comment]
Thanks for flagging this up. DataTables has number detection that allows for locales and thousands separators, so it might be that this can be exposed in a public API and used. The "numbers" would also have to be deformatted so they can be written into the XML as just a plain number with a `.` for decimal and no thousands separators.

It is this latter part which might make this a little more difficult. I'll look at exposing this ability in the next version of DataTables. I'm afraid this issue likely won't be fixed in the short term.

**Comment by DataTables** [comment]
Buttons 1.2 introduce a number of formatting testers for numbers in order to retain the original formatting. It doesn't yet support a comma as a decimal place, but that is something that I plan to do in future.

**Comment by tronics** [comment]
You please have to take into account that in Europe (Austria and Germany) the Excel Version has different settings than US:

1) So they expect decimal , prices as in this bugreport. Thank you for recognizing it.
2) But also the workaround does not work.
The **default delimiters of our Excel settings** do not work for opening the csv export. 
Changing the settings is not really an option if you work with other csv files.

So here are 2 problems that are connected.
